# -*- coding: utf-8 -*-
"""Streamlit Dana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFCxX44ZUcSA1_oeY5_cyPRC1rrvgadE
"""

!pip install -q streamlit plotly pandas

import streamlit as st
import plotly.express as px
import pandas as pd
print("OK")